In [2]:
import numpy as np
import pandas as pd

In [3]:
student_data = {
    'Student': ['Sam', 'Alex', 'Ryan', 'Maya', 'Liam'],
    'Subject': ['Math', 'Math', 'Science', 'Science', 'Math'],
    'Score': [85, 42, 90, 78, 55],
    'Passed': [True, False, True, True, False]
}
df = pd.DataFrame(student_data)

In [4]:
df

  Student  Subject  Score  Passed
0     Sam     Math     85    True
1    Alex     Math     42   False
2    Ryan  Science     90    True
3    Maya  Science     78    True
4    Liam     Math     55   False

In [6]:
df.shape

(5, 4)

In [7]:
df.columns

Index(['Student', 'Subject', 'Score', 'Passed'], dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Student  5 non-null      object
 1   Subject  5 non-null      object
 2   Score    5 non-null      int64
 3   Passed   5 non-null      bool
dtypes: bool(1), int64(1), object(2)
memory usage: 257.0+ bytes

In [10]:
df.describe()

           Score
count   5.000000
mean   70.000000
std    20.603398
min    42.000000
25%    55.000000
50%    78.000000
75%    85.000000
max    90.000000

In [11]:
df['Score'] + 20

0    105
1     62
2    110
3     98
4     75
Name: Score, dtype: int64

In [12]:
#APPLYING FUNCTIONS