In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('/home/ashwini/Documents/DataPreprocessing/dash_implementation/data/wfp_food_prices_database.csv')

/tmp/ipykernel_261954/2041797851.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/home/ashwini/Documents/DataPreprocessing/dash_implementation/data/wfp_food_prices_database.csv')

In [5]:
df.head(10)

,adm0_id,adm0_name,adm1_id,adm1_name,mkt_id,mkt_name,cm_id,cm_name,cur_id,cur_name,pt_id,pt_name,um_id,um_name,mp_month,mp_year,mp_price,mp_commoditysource
0,1.0,Afghanistan,272,Badakhshan,266,Fayzabad,55,Bread - Retail,0.0,AFN,15,Retail,5,KG,1,2014,50.0,NaN
1,1.0,Afghanistan,272,Badakhshan,266,Fayzabad,55,Bread - Retail,0.0,AFN,15,Retail,5,KG,2,2014,50.0,NaN
2,1.0,Afghanistan,272,Badakhshan,266,Fayzabad,55,Bread - Retail,0.0,AFN,15,Retail,5,KG,3,2014,50.0,NaN
3,1.0,Afghanistan,272,Badakhshan,266,Fayzabad,55,Bread - Retail,0.0,AFN,15,Retail,5,KG,4,2014,50.0,NaN
4,1.0,Afghanistan,272,Badakhshan,266,Fayzabad,55,Bread - Retail,0.0,AFN,15,Retail,5,KG,5,2014,50.0,NaN
5,1.0,Afghanistan,272,Badakhshan,266,Fayzabad,55,Bread - Retail,0.0,AFN,15,Retail,5,KG,6,2014,50.0,NaN
6,1.0,Afghanistan,272,Badakhshan,266,Fayzabad,55,Bread - Retail,0.0,AFN,15,Retail,5,KG,7,2014,50.0,NaN
7,1.0,Afghanistan,272,Badakhshan,266,Fayzabad,55,Bread - Retail,0.0,AFN,15,Retail,5,KG,8,2014,50.0,NaN
8,1.0,Afghanistan,272,Badakhshan,266,Fayzabad,55,Bread - Retail,0.0,AFN,15,Retail,5,KG,9,2014,50.0,NaN
9,1.0,Afghanistan,272,Badakhshan,266,Fayzabad,55,Bread - Retail,0.0,AFN,15,Retail,5,KG,10,2014,50.0,NaN

In [7]:
df.shape

(1560551, 18)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1560551 entries, 0 to 1560550
Data columns (total 18 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   adm0_id             1560551 non-null  float64
 1   adm0_name           1560551 non-null  object
 2   adm1_id             1560551 non-null  int64
 3   adm1_name           1089223 non-null  object
 4   mkt_id              1560551 non-null  int64
 5   mkt_name            1560551 non-null  object
 6   cm_id               1560551 non-null  int64
 7   cm_name             1560551 non-null  object
 8   cur_id              1560551 non-null  float64
 9   cur_name            1560551 non-null  object
 10  pt_id               1560551 non-null  int64
 11  pt_name             1560551 non-null  object
 12  um_id               1560551 non-null  int64
 13  um_name             1560551 non-null  object
 14  mp_month            1560551 non-null  int64
 15  mp_year             1560551 non-null  int64
 16  mp_price            1560551 non-null  float64
 17  mp_commoditysource  0 non-null        float64
dtypes: float64(4), int64(7), object(7)
memory usage: 214.3+ MB

In [9]:
df.describe()

,adm0_id,adm1_id,mkt_id,cm_id,cur_id,pt_id,um_id,mp_month,mp_year,mp_price,mp_commoditysource
count,1.560551e+06,1.560551e+06,1.560551e+06,1.560551e+06,1560551.0,1.560551e+06,1.560551e+06,1.560551e+06,1.560551e+06,1.560551e+06,0.0
mean,9.844180e+02,2.754153e+04,1.264696e+03,1.881567e+02,0.0,1.491051e+01,1.442846e+01,6.354202e+00,2.014892e+03,6.136956e+03,NaN
std,6.950778e+03,1.236072e+05,8.436958e+02,1.502811e+02,0.0,2.958780e-01,2.368151e+01,3.391472e+00,4.382253e+00,1.217337e+05,NaN
min,1.000000e+00,0.000000e+00,8.000000e+01,5.000000e+01,0.0,1.400000e+01,5.000000e+00,1.000000e+00,1.990000e+03,0.000000e+00,NaN
25%,1.080000e+02,1.572000e+03,5.340000e+02,7.100000e+01,0.0,1.500000e+01,5.000000e+00,3.000000e+00,2.013000e+03,3.540000e+01,NaN
50%,1.550000e+02,2.205000e+03,1.075000e+03,1.200000e+02,0.0,1.500000e+01,5.000000e+00,6.000000e+00,2.016000e+03,2.062500e+02,NaN
75%,2.050000e+02,3.433000e+03,1.895000e+03,2.770000e+02,0.0,1.500000e+01,9.000000e+00,9.000000e+00,2.018000e+03,8.250000e+02,NaN
max,7.000100e+04,9.000220e+05,4.083000e+03,8.380000e+02,0.0,1.800000e+01,1.640000e+02,1.200000e+01,2.020000e+03,2.177778e+07,NaN

In [10]:
df.isnull().sum()

adm0_id                     0
adm0_name                   0
adm1_id                     0
adm1_name              471328
mkt_id                      0
mkt_name                    0
cm_id                       0
cm_name                     0
cur_id                      0
cur_name                    0
pt_id                       0
pt_name                     0
um_id                       0
um_name                     0
mp_month                    0
mp_year                     0
mp_price                    0
mp_commoditysource    1560551
dtype: int64

In [15]:
df[['adm0_id','adm1_name','mp_commoditysource']]

         adm0_id   adm1_name  mp_commoditysource
0            1.0  Badakhshan                 NaN
1            1.0  Badakhshan                 NaN
2            1.0  Badakhshan                 NaN
3            1.0  Badakhshan                 NaN
4            1.0  Badakhshan                 NaN
...          ...         ...                 ...
1560546    271.0    Midlands                 NaN
1560547    271.0    Midlands                 NaN
1560548    271.0    Midlands                 NaN
1560549    271.0    Midlands                 NaN
1560550    271.0    Midlands                 NaN

[1560551 rows x 3 columns]